<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="3" ignored="3" total="8" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-01-28T12:52:02 IST" name="Default suite" finished-at="2025-01-28T12:52:40 IST" duration-ms="38157">
    <groups>
      <group name="Sanity">
        <method signature="TC_006.contacts_003()[pri:0, instance:tcRepo.TC_006@2af004b]" name="contacts_003" class="tcRepo.TC_006"/>
      </group> <!-- Sanity -->
      <group name="Smoke">
        <method signature="TC_006.contacts_003()[pri:0, instance:tcRepo.TC_006@2af004b]" name="contacts_003" class="tcRepo.TC_006"/>
      </group> <!-- Smoke -->
    </groups>
    <test started-at="2025-01-28T12:52:02 IST" name="Default test" finished-at="2025-01-28T12:52:40 IST" duration-ms="38157">
      <class name="tcRepo.TC_006">
        <test-method is-config="true" signature="dbConnection()[pri:0, instance:tcRepo.TC_006@2af004b]" started-at="2025-01-28T12:52:02 IST" name="dbConnection" finished-at="2025-01-28T12:52:02 IST" duration-ms="10" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dbConnection -->
        <test-method is-config="true" signature="launchBrowser(java.lang.String)[pri:0, instance:tcRepo.TC_006@2af004b]" started-at="2025-01-28T12:52:02 IST" name="launchBrowser" finished-at="2025-01-28T12:52:05 IST" duration-ms="3072" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method is-config="true" signature="loginOperation()[pri:0, instance:tcRepo.TC_006@2af004b]" started-at="2025-01-28T12:52:05 IST" name="loginOperation" finished-at="2025-01-28T12:52:07 IST" duration-ms="2269" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginOperation -->
        <test-method signature="contacts_003()[pri:0, instance:tcRepo.TC_006@2af004b]" started-at="2025-01-28T12:52:07 IST" name="contacts_003" finished-at="2025-01-28T12:52:18 IST" duration-ms="10954" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- contacts_003 -->
        <test-method is-config="true" signature="logoutOperation()[pri:0, instance:tcRepo.TC_006@2af004b]" started-at="2025-01-28T12:52:18 IST" name="logoutOperation" finished-at="2025-01-28T12:52:19 IST" duration-ms="1172" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutOperation -->
        <test-method is-config="true" signature="loginOperation()[pri:0, instance:tcRepo.TC_006@2af004b]" started-at="2025-01-28T12:52:19 IST" name="loginOperation" finished-at="2025-01-28T12:52:22 IST" duration-ms="2232" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginOperation -->
        <test-method retried="true" signature="parallelTest()[pri:0, instance:tcRepo.TC_006@2af004b]" started-at="2025-01-28T12:52:22 IST" name="parallelTest" finished-at="2025-01-28T12:52:22 IST" duration-ms="11" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at tcRepo.TC_006.parallelTest(TC_006.java:37)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- parallelTest -->
        <test-method is-config="true" signature="logoutOperation()[pri:0, instance:tcRepo.TC_006@2af004b]" started-at="2025-01-28T12:52:22 IST" name="logoutOperation" finished-at="2025-01-28T12:52:25 IST" duration-ms="2956" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutOperation -->
        <test-method is-config="true" signature="loginOperation()[pri:0, instance:tcRepo.TC_006@2af004b]" started-at="2025-01-28T12:52:25 IST" name="loginOperation" finished-at="2025-01-28T12:52:27 IST" duration-ms="2151" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginOperation -->
        <test-method retried="true" signature="parallelTest()[pri:0, instance:tcRepo.TC_006@2af004b]" started-at="2025-01-28T12:52:27 IST" name="parallelTest" finished-at="2025-01-28T12:52:27 IST" duration-ms="2" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at tcRepo.TC_006.parallelTest(TC_006.java:37)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:249)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- parallelTest -->
        <test-method is-config="true" signature="logoutOperation()[pri:0, instance:tcRepo.TC_006@2af004b]" started-at="2025-01-28T12:52:27 IST" name="logoutOperation" finished-at="2025-01-28T12:52:30 IST" duration-ms="2936" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutOperation -->
        <test-method is-config="true" signature="loginOperation()[pri:0, instance:tcRepo.TC_006@2af004b]" started-at="2025-01-28T12:52:30 IST" name="loginOperation" finished-at="2025-01-28T12:52:32 IST" duration-ms="1931" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginOperation -->
        <test-method retried="true" signature="parallelTest()[pri:0, instance:tcRepo.TC_006@2af004b]" started-at="2025-01-28T12:52:32 IST" name="parallelTest" finished-at="2025-01-28T12:52:32 IST" duration-ms="3" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at tcRepo.TC_006.parallelTest(TC_006.java:37)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:249)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- parallelTest -->
        <test-method is-config="true" signature="logoutOperation()[pri:0, instance:tcRepo.TC_006@2af004b]" started-at="2025-01-28T12:52:32 IST" name="logoutOperation" finished-at="2025-01-28T12:52:35 IST" duration-ms="3098" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutOperation -->
        <test-method is-config="true" signature="loginOperation()[pri:0, instance:tcRepo.TC_006@2af004b]" started-at="2025-01-28T12:52:35 IST" name="loginOperation" finished-at="2025-01-28T12:52:37 IST" duration-ms="1929" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginOperation -->
        <test-method signature="parallelTest()[pri:0, instance:tcRepo.TC_006@2af004b]" started-at="2025-01-28T12:52:37 IST" name="parallelTest" finished-at="2025-01-28T12:52:37 IST" duration-ms="6" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at tcRepo.TC_006.parallelTest(TC_006.java:37)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:249)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- parallelTest -->
        <test-method is-config="true" signature="logoutOperation()[pri:0, instance:tcRepo.TC_006@2af004b]" started-at="2025-01-28T12:52:37 IST" name="logoutOperation" finished-at="2025-01-28T12:52:40 IST" duration-ms="3106" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutOperation -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:tcRepo.TC_006@2af004b]" started-at="2025-01-28T12:52:40 IST" name="closeBrowser" finished-at="2025-01-28T12:52:40 IST" duration-ms="233" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="dbConnectionClosed()[pri:0, instance:tcRepo.TC_006@2af004b]" started-at="2025-01-28T12:52:40 IST" name="dbConnectionClosed" finished-at="2025-01-28T12:52:40 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dbConnectionClosed -->
      </class> <!-- tcRepo.TC_006 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
